name = "github"
bat_theme = "GitHub"

[styles.header]
fg = "#333333"
bg = "#ffffff"

[styles.row_highlight]
fg = "#795da3"
bg = "#b0cde7"

[styles.prompt]
fg = "#a71d5d"

[styles.empty]
fg = "#9d9d9d"

[styles.highlight]
fg = "#795da3"
modifiers = ["bold"]
