name = "light"

[styles.header]
fg = "#0f172a"
bg = "#e2e8f0"

[styles.row_highlight]
fg = "#787800"
bg = "#c8c8c8"

[styles.prompt]
fg = "#006699"

[styles.empty]
fg = "#646464"

[styles.highlight]
fg = "#787800"
modifiers = ["bold"]
