name = "slate"
aliases = ["default"]
default = true

[styles.header]
fg = "#e2e8f0"
bg = "#0f172a"

[styles.row_highlight]
fg = "#facd15"
bg = "#1e293b"

[styles.prompt]
fg = "light_cyan"

[styles.empty]
fg = "dark_gray"

[styles.highlight]
fg = "yellow"
modifiers = ["bold"]
