name = "solarized"

[styles.header]
fg = "#fdf6e3"
bg = "#073642"

[styles.row_highlight]
fg = "#b58900"
bg = "#002b36"

[styles.prompt]
fg = "#268bd2"

[styles.empty]
fg = "#586e75"

[styles.highlight]
fg = "#b58900"
modifiers = ["bold"]
