name = "solarized-light"
bat_theme = "Solarized (light)"

[styles.header]
fg = "#073642"
bg = "#fdf6e3"

[styles.row_highlight]
fg = "#b58900"
bg = "#eee8d5"

[styles.prompt]
fg = "#859900"

[styles.empty]
fg = "#93a1a1"

[styles.highlight]
fg = "#b58900"
modifiers = ["bold"]
